# Generated by Django 3.0.6 on 2020-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200508_2054'),
        ('authentication', '0002_auto_20200512_0658'),
    ]

    operations = [
    ]
